//package com.example.DynamoDB.entity;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.*;
//import lombok.AllArgsConstructor;
//import lombok.Builder;
//import lombok.Data;
//import lombok.NoArgsConstructor;
//
//
//@Data
//@NoArgsConstructor
//@AllArgsConstructor
//@DynamoDBTable(tableName = "Student")
//@Builder
//public class StudentEntity {
//
//    @DynamoDBHashKey
////    @DynamoDBAutoGeneratedKey
//    private String studentId;
//
//    private String firstName;
//    private String lastName;
//
//    private Department department;
//}
